// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TunaPiano_BE.Migrations
{
    [DbContext(typeof(TunaPiano_BEDbContext))]
    [Migration("20240906220650_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GenreSong", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("integer");

                    b.Property<int>("SongsId")
                        .HasColumnType("integer");

                    b.HasKey("GenresId", "SongsId");

                    b.HasIndex("SongsId");

                    b.ToTable("GenreSong");
                });

            modelBuilder.Entity("TunaPiano_BE.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 32,
                            Bio = "Nigerian singer and songwriter known for his fusion of Afrobeat and other genres",
                            Name = "Burna Boy"
                        },
                        new
                        {
                            Id = 2,
                            Age = 27,
                            Bio = "Nigerian singer and songwriter known for her soulful voice and introspective lyrics",
                            Name = "Tems"
                        },
                        new
                        {
                            Id = 3,
                            Age = 55,
                            Bio = "French DJ and record producer known for EDM hits",
                            Name = "David Guetta"
                        },
                        new
                        {
                            Id = 4,
                            Age = 27,
                            Bio = "Dutch DJ and record producer known for his EDM tracks",
                            Name = "Martin Garrix"
                        },
                        new
                        {
                            Id = 5,
                            Age = 40,
                            Bio = "Legendary jazz trumpeter and composer",
                            Name = "Miles Davis"
                        },
                        new
                        {
                            Id = 6,
                            Age = 42,
                            Bio = "Saxophonist known for his innovative jazz playing",
                            Name = "John Coltrane"
                        },
                        new
                        {
                            Id = 7,
                            Age = 55,
                            Bio = "Grammy-winning gospel singer and producer",
                            Name = "Kirk Franklin"
                        },
                        new
                        {
                            Id = 8,
                            Age = 40,
                            Bio = "Gospel singer known for her powerful vocals",
                            Name = "Tasha Cobbs Leonard"
                        });
                });

            modelBuilder.Entity("TunaPiano_BE.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Afrobeat"
                        },
                        new
                        {
                            Id = 2,
                            Description = "EDM"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Jazz"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Gospel"
                        });
                });

            modelBuilder.Entity("TunaPiano_BE.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<double>("Length")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Album = "Love, Damini",
                            ArtistId = 1,
                            Length = 240.5,
                            Title = "Last Last"
                        },
                        new
                        {
                            Id = 2,
                            Album = "If Orange Was the Color of Sky",
                            ArtistId = 2,
                            Length = 210.19999999999999,
                            Title = "Free Mind"
                        },
                        new
                        {
                            Id = 3,
                            Album = "Nothing But the Beat",
                            ArtistId = 3,
                            Length = 270.80000000000001,
                            Title = "Play Hard"
                        },
                        new
                        {
                            Id = 4,
                            Album = "Animals",
                            ArtistId = 4,
                            Length = 255.30000000000001,
                            Title = "Animals"
                        },
                        new
                        {
                            Id = 5,
                            Album = "Kind of Blue",
                            ArtistId = 5,
                            Length = 300.0,
                            Title = "So What"
                        },
                        new
                        {
                            Id = 6,
                            Album = "Giant Steps",
                            ArtistId = 6,
                            Length = 285.69999999999999,
                            Title = "Giant Steps"
                        },
                        new
                        {
                            Id = 7,
                            Album = "The Rebirth",
                            ArtistId = 7,
                            Length = 220.09999999999999,
                            Title = "Stomp"
                        },
                        new
                        {
                            Id = 8,
                            Album = "Grace",
                            ArtistId = 8,
                            Length = 235.59999999999999,
                            Title = "Break Every Chain"
                        },
                        new
                        {
                            Id = 9,
                            Album = "Twice as Tall",
                            ArtistId = 1,
                            Length = 260.89999999999998,
                            Title = "Ye"
                        },
                        new
                        {
                            Id = 10,
                            Album = "If Orange Was the Color of Sky",
                            ArtistId = 2,
                            Length = 200.40000000000001,
                            Title = "Vibez"
                        },
                        new
                        {
                            Id = 11,
                            Album = "Nothing But the Beat",
                            ArtistId = 3,
                            Length = 290.19999999999999,
                            Title = "Titanium"
                        },
                        new
                        {
                            Id = 12,
                            Album = "Animals",
                            ArtistId = 4,
                            Length = 275.5,
                            Title = "In My Mind"
                        },
                        new
                        {
                            Id = 13,
                            Album = "Kind of Blue",
                            ArtistId = 5,
                            Length = 310.69999999999999,
                            Title = "So What"
                        },
                        new
                        {
                            Id = 14,
                            Album = "Giant Steps",
                            ArtistId = 6,
                            Length = 295.10000000000002,
                            Title = "Giant Steps"
                        },
                        new
                        {
                            Id = 15,
                            Album = "The Rebirth",
                            ArtistId = 7,
                            Length = 215.80000000000001,
                            Title = "Stomp"
                        },
                        new
                        {
                            Id = 16,
                            Album = "Grace",
                            ArtistId = 8,
                            Length = 230.30000000000001,
                            Title = "Break Every Chain"
                        },
                        new
                        {
                            Id = 17,
                            Album = "Twice as Tall",
                            ArtistId = 1,
                            Length = 250.59999999999999,
                            Title = "On The Low"
                        },
                        new
                        {
                            Id = 18,
                            Album = "If Orange Was the Color of Sky",
                            ArtistId = 2,
                            Length = 190.09999999999999,
                            Title = "For Now"
                        },
                        new
                        {
                            Id = 19,
                            Album = "Nothing But the Beat",
                            ArtistId = 3,
                            Length = 280.39999999999998,
                            Title = "When Love Takes Over"
                        },
                        new
                        {
                            Id = 20,
                            Album = "Animals",
                            ArtistId = 4,
                            Length = 265.69999999999999,
                            Title = "Animals"
                        });
                });

            modelBuilder.Entity("GenreSong", b =>
                {
                    b.HasOne("TunaPiano_BE.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TunaPiano_BE.Models.Song", null)
                        .WithMany()
                        .HasForeignKey("SongsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TunaPiano_BE.Models.Song", b =>
                {
                    b.HasOne("TunaPiano_BE.Models.Artist", "Artist")
                        .WithMany("Songs")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("TunaPiano_BE.Models.Artist", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
